const products = [
	{
		id: 0,
		name: 'Валенсия Beige',
		price: 2300,
		instock: 100,
		category: 'Барные стулья',
		imgSrc: './images/content/bestsellers/bestellers-1.jpg',
	},
	{
		id: 1,
		name: 'Толикс-2 White Gloss',
		price: 4690,
		instock: 60,
		category: 'Барные стулья',
		imgSrc: './images/content/bestsellers/bestellers-2.jpg',
	},
	{
		id: 2,
		name: 'Динс Velvet Yellow',
		price: 28490,
		instock: 5,
		category: 'Диваны',
		imgSrc: './images/content/bestsellers/bestellers-3.jpg',
	},
	{
		id: 3,
		name: 'Кускен Navy Blue',
		price: 22300,
		instock: 20,
		category: 'Диваны',
		imgSrc: './images/content/bestsellers/bestellers-4.jpg',
	},
	{
		id: 4,
		name: 'Шерона Barhat Grey',
		price: 21990,
		instock: 10,
		category: 'Двухспальные кровати',
		imgSrc: './images/content/bestsellers/bestellers-5.jpg',
	},
	{
		id: 5,
		name: 'Авиньон-1',
		price: 18990,
		instock: 12,
		category: 'Буфеты',
		imgSrc: './images/content/bestsellers/bestellers-6.jpg',
	},
	{
		id: 6,
		name: 'Стелла Дуб Сонома',
		price: 8990,
		instock: 17,
		category: 'Комоды',
		imgSrc: './images/content/bestsellers/bestellers-7.jpg',
	},
	{
		id: 7,
		name: 'Равенна-1 Light',
		price: 14990,
		instock: 20,
		category: 'Комоды',
		imgSrc: './images/content/bestsellers/bestellers-8.jpg',
	},
	{
		id: 8,
		name: 'Бенфлит Grey',
		price: 7200,
		instock: 30,
		category: 'Журнальные столы',
		imgSrc: './images/content/bestsellers/bestellers-9.jpg',
	},
	{
		id: 9,
		name: 'Тиффани Вудлайн Крем',
		price: 10990,
		instock: 9,
		category: 'Письменные столы',
		imgSrc: './images/content/bestsellers/bestellers-10.jpg',
	},
	{
		id: 10,
		name: 'Валенсия Beige',
		price: 19990,
		instock: 14,
		category: 'Шкафы',
		imgSrc: './images/content/bestsellers/bestellers-11.jpg',
	},
	{
		id: 11,
		name: 'Лайт-3-170-240 Белый',
		price: 27990,
		instock: 11,
		category: 'Шкафы',
		imgSrc: './images/content/bestsellers/bestellers-12.jpg',
	},
	{
		id: 12,
		name: 'Вилли Pink',
		price: 21990,
		instock: 21,
		category: 'Детская мебель',
		imgSrc: './images/content/bestsellers/bestellers-13.jpg',
	},
	{
		id: 13,
		name: 'Сан-Паулу Velvet Brown',
		price: 18990,
		instock: 18,
		category: 'Диваны',
		imgSrc: './images/content/bestsellers/bestellers-14.jpg',
	},
	{
		id: 14,
		name: 'Стеллаж Варди',
		price: 10990,
		instock: 22,
		category: 'Стеллажи',
		imgSrc: './images/content/bestsellers/bestellers-15.jpg',
	},
	{
		id: 15,
		name: 'Стеллаж модульный Ариана',
		price: 12990,
		instock: 25,
		category: 'Стеллажи',
		imgSrc: './images/content/bestsellers/bestellers-16.jpg',
	},
];
